name: CI/CD Pipeline - Build, Push and Deploy to Minikube # Pipeline adını güncelledik

on:
  push:
    branches:
      - master # Kodu push ettiğiniz branch'in adı (master olarak varsayıyoruz)

jobs:
  build-push-deploy: # Job adını güncelledik
    # Kendi runner'ınızın etiketini kullanın (örn: minikube-runner veya self-hosted)
    runs-on: minikube-runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: . # Dockerfile'ınızın bulunduğu dizin (genellikle proje kökü)
        push: true
        # Image adınız ve tag'lerinizi güncellemeyi unutmayın!
        tags: alpayakyilmaz/myappimage:${{ github.sha }},alpayakyilmaz/myappimage:latest

    # --- Minikube Deployment Adımları ---
    # Kubeconfig dosyasını hazırlar.
    - name: Setup Kubeconfig for Minikube
      run: |
        New-Item -Path "~/.kube" -ItemType Directory -ErrorAction SilentlyContinue
        [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.KUBE_CONFIG_BASE64 }}")) | Out-File -FilePath ~/.kube/config -Encoding UTF8
      shell: powershell
    - name: Verify Kubeconfig Content # YENİ DEBUG ADIMI
      run: |
       Get-Content ~/.kube/config # Kubeconfig dosyasının içeriğini yazdırır
      shell: powershell
    - name: Deploy to Minikube
      run: |
        kubectl apply -f deployment.yaml # deployment.yaml deponun kök dizininde olduğu varsayılıyor
      env:
        KUBECONFIG: ~/.kube/config
      shell: powershell