name: CI/CD Pipeline - Build, Push and Deploy to K8s

on:
  push:
    branches:
      - master

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Image Tag
      id: image_tag
      run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/aspnetcore-sample-app:${{ env.IMAGE_TAG }} \
                     -t ${{ secrets.DOCKER_USERNAME }}/aspnetcore-sample-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/aspnetcore-sample-app:${{ env.IMAGE_TAG }}
        docker push ${{ secrets.DOCKER_USERNAME }}/aspnetcore-sample-app:latest

    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config

    - name: Update K8s Deployment with New Image
      run: |
        kubectl set image deployment/my-dotnet-app-deployment \
        my-dotnet-app-container=${{ secrets.DOCKER_USERNAME }}/aspnetcore-sample-app:${{ env.IMAGE_TAG }} \
        --record
