name: CI/CD Pipeline - Build, Push and Deploy to Minikube # Pipeline adını güncelledik

on:
  push:
    branches:
      - master # Kodu push ettiğiniz branch'in adı (master olarak varsayıyoruz)

jobs:
  build-push-deploy: # Job adını güncelledik
    # BURAYI KENDİ RUNNER'INIZIN ETİKETİYLE GÜNCELLEYİN!
    # Eğer yapılandırırken 'minikube-runner' verdiyseniz, aşağıdaki gibi kullanın:
    runs-on: minikube-runner # Veya 'self-hosted' de kullanabilirsiniz eğer sadece bir self-hosted runner'ınız varsa

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: . # Dockerfile'ınızın bulunduğu dizin (genellikle proje kökü)
        push: true
        # Image adınızı ve tag'lerinizi güncellemeyi unutmayın!
        # Daha önce belirlediğimiz gibi: alpayakyilmaz/myappimage
        tags: alpayakyilmaz/myappimage:${{ github.sha }},alpayakyilmaz/myappimage:latest

    # --- Minikube Deployment Adımlarını GERİ GETİRİYORUZ ---
    # Bu adımlar, Kubeconfig dosyasını hazırlar ve uygulamanızı dağıtır.
    - name: Setup Kubeconfig for Minikube
      run: |
        # Bu dizini Windows'ta da oluşturduğundan emin olun
        # Mevcutsa hata vermeden geçmesi için -ErrorAction SilentlyContinue kullanın
        New-Item -Path "~/.kube" -ItemType Directory -ErrorAction SilentlyContinue
        # Kubeconfig dosyasını GitHub Secrets'tan çekip Base64'ten çözerek dosyaya yazar
        [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("${{ secrets.KUBE_CONFIG_BASE64 }}")) | Out-File -FilePath ~/.kube/config -Encoding UTF8
        # Dosya izinlerini ayarlar (Linux/macOS için önemli, Windows için iyi bir pratik)
        #chmod 600 ~/.kube/config
      shell: powershell # Shell'i açıkça powershell olarak belirtmek daha güvenli olabilir
    - name: Deploy to Minikube
      run: |        
        kubectl apply -f deployment.yaml # Güncellenmiş YAML'ı Minikube'ye uygula
      env:
        KUBECONFIG: ~/.kube/config # kubectl'in doğru kubeconfig'i kullanmasını sağlar
      shell: powershell