name: Build and Deploy

on:
  push:
    branches:
      - master  # veya main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set IMAGE_TAG as current datetime
      id: tag
      run: echo "IMAGE_TAG=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/aspnetcore-sample-app:${{ steps.tag.outputs.IMAGE_TAG }} .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/aspnetcore-sample-app:${{ steps.tag.outputs.IMAGE_TAG }}

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG_BASE64 }}" | base64 -d > $HOME/.kube/config

    - name: Update Deployment with new image
      run: |
        kubectl set image deployment/my-dotnet-app-deployment \
        my-dotnet-app-container=${{ secrets.DOCKER_USERNAME }}/aspnetcore-sample-app:${{ steps.tag.outputs.IMAGE_TAG }}
        kubectl rollout status deployment/my-dotnet-app-deployment
